### ISSUE TITLE
default behaviour of adapter contamination test has changed

### ISSUE THREAD

**Issue by AndreasHeger** [CGATOxford/CGATPipelines#26]
While previously the test data was a PASS, now the section is empty and it is a WARN.

Is this intended?

**Comment by MikeDMorgan** [comment]
I'll investigate.  Following implementation of the automatic contamination removal function FastQC changed versions, subsequently the way that it reports and stores overrepresented sequences and adaptor contamination has changed.  This may be the reason.

**Comment by MikeDMorgan** [comment]
The current behaviour results fromm incorrect parsing of the contaminants file.  In the absence of an adaptor contaminants file Fastqc will attempt to detect common adaptor sequence contamination over reads and output a histogram approapriately.  This is however based on common 12mers and may not indicate genuine contamination.  Instead the actual adaptor sequnces can be provided for this module, however, these sequences are longer than the test data reads, thus it will provide a WARN instead of a PASS.

Proposed solution: look at read length, if less than adaptor sequences then use default behaviour, else use user-provided contamination file.

**Comment by AndreasHeger** [comment]
Thanks, this has been fixed!
