### ISSUE TITLE
regex_linecount and regex_exist tests not picking up files

### ISSUE THREAD

**Issue by KatyBrown** [CGATOxford/CGATPipelines#309]
Hi,

I think there is a problem regex_linecount and regex_exist pipeline.ini options in the pipeline tests.

For example, looking at pipeline_annotations:
In the pipeline.ini the configuration is:
[test_annotations]
target=assembly,geneset,annotations,ucsc,summary
suffixes=gff.gz,gtf.gz,bed.gz,tsv.gz,fasta
regex_exist=gwas_catalog|gwas_distild|goslim.tsv.gz|genomic_function.*.gz|kegg.tsv.gz

But the pipeline_annotations.ref file in /ifs/projects/pipelines does not contain any of the files which match regex_exist.  It also doesn't include any file ending with kegg.tsv.gz, even though this would match the tsv.gz suffix in the suffixes parameter.

For pipeline_readqc it is different:

The pipeline.ini section is:
[test_readqc]
suffixes=tsv.gz,fastqc,_data.txt,summary.txt
regex_linecount=fastqc_data.txt

This time the files ending with fastqc_data.txt are in testing_readqc.ref

So I don't understand what's happening!

Thanks very much,
Katy

**Comment by sebastian-luna-valero** [comment]
Thanks @KatyBrown 

I am looking at this.

**Comment by sebastian-luna-valero** [comment]
I can see the problem now.

The `buildLineCounts` task uses `suffixes` instead of `regex_linecount` to count lines:
https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/pipeline_testing.py#L367

Moreover, `mergeFileStatistics` uses bash's `join` command:
https://github.com/CGATOxford/CGATPipelines/blob/master/CGATPipelines/pipeline_testing.py#L395

which will only output the information for those files which are in common between `suffixes` and `regex_linecount` regular expressions, and therefore discard those belonging to a single category.

I will open a PR providing a solution for this.

**Comment by AndreasHeger** [comment]
Thanks!

**Comment by sebastian-luna-valero** [comment]
Sorry for the delay, I found several other issues with `pipeline_testing` along the way.

These pull requests should solve them all:
* https://github.com/CGATOxford/CGATPipelines/pull/316
* https://github.com/CGATOxford/CGATTests/pull/3

I have merged into master and will also update all tests in Jenkins accordingly.

Many thanks for your patient.

**Comment by Charlie-George** [comment]
Thanks Sebastian!

On 20 Apr 2017, at 14:26, Sebastian Luna-Valero <notifications@github.com<mailto:notifications@github.com>> wrote:


Sorry for the delay, I found several other issues with pipeline_testing along the way.

These pull requests should solve them all:

  *   #316<https://github.com/CGATOxford/CGATPipelines/pull/316>
  *   CGATOxford/CGATTests#3<https://github.com/CGATOxford/CGATTests/pull/3>

I have merged into master and will also update all tests in Jenkins accordingly.

Many thanks for your patient.
