### ISSUE TITLE
Result list has a small error generated by rnaseqdiffexpression.py 

### ISSUE THREAD

**Issue by XijinXu** [CGATOxford/CGATPipelines#317]
The DE gene list I got from pipeline_rnaseqdiffexpression.py is right, except that the control group mean value and the treatment  group mean value is the same number. One of them is wrong I think. 
It doesn't affect the data interpretation, but it would be great if it can be fixed. Thanks!

**Comment by KatyBrown** [comment]
Hi Xijin - can you send me the link to the output file that is wrong?

**Comment by XijinXu** [comment]
Hi Katy,

Thank you very much!
Here is the path:
/ifs/projects/proj066/P140478_mRNA/pipeline_DE_coding/DEresults.dir/deseq2/featurecounts__1_genes_results.tsv

Best wishes,
Xijin
________________________________

**Comment by TomSmithCGAT** [comment]
Hi @XijinXu. From memory, this is because the pipeline uses the output from [count2table.py](https://github.com/CGATOxford/cgat/blob/master/CGAT/scripts/counts2table.py) which takes the output for each differential expression tool and reformats this into a generic  Since some tools (e.g DESeq2) don't give the average expression in the two groups, but rather the average expression across all samples, this is used to populate the control group mean and treatment group mean columns. This should been made clearer.

Theoretically, it shouldn't be difficult to derive the actual mean control/treatment expression values rather than relying on the output from the differential expression tool output alone.

**Comment by XijinXu** [comment]
Hi Tom, that make sense! DEseq2 and edger both produce average expression in the two groups. Maybe we should change the title in the genelist, because it is a littile misleading. 
Thank you! :)

**Comment by Acribbs** [comment]
I will update the pipeline and change the naming as i agree its a confusing
