### ISSUE TITLE
pandas module is deprecated 

### ISSUE THREAD

**Issue by Acribbs** [CGATOxford/CGATPipelines#378]
@sebastian-luna-valero ,

I have noticed on a number of pipelines we are getting warnings that pandas modules are deprecated, specifically pandas.lib and pandas.core.datetools.

I think we should change pandas import statements so this doesn't happened, please see: https://github.com/yhat/ggpy/issues/618

**Comment by sebastian-luna-valero** [comment]
Thanks @Acribbs 

I am getting those as well, but looking deeper into them, this is caused by `CGATReport`, `ggplot`, and `statsmodels`:
```
/conda-install/envs/cgat-p/lib/python3.6/site-packages/CGATReport/DataTree.py:267: FutureWarning: '.reindex_axis' is deprecated and will be removed in a future version. Use '.reindex' instead.
/conda-install/envs/cgat-p/lib/python3.6/site-packages/ggplot/components/smoothers.py:4: FutureWarning: The pandas.lib module is deprecated and will be removed in a future version. These are private functions and can be accessed from pandas._libs.lib instead
/conda-install/envs/cgat-p/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
```
So AFAIK, the refactoring should happen on those packages rather than in our pipelines. Presumably this will occur in new versions of those packages, and the `FutureWarning` will disappear after we upgrade our conda environments.

Will close but feel free to re-open if necessary.
