### ISSUE TITLE
No transcript_info table with pipeline_genesets

### ISSUE THREAD

**Issue by TomSmithCGAT** [CGATOxford/CGATPipelines#434]
pipeline_annotations used to make a table called `transcript_info` https://github.com/CGATOxford/CGATPipelines/blob/94b975256fa5142f15e82511f4b62a6c19ae38b9/obsolete/pipeline_annotations.py#L1049-L1054 which is used in multiple pipeline, for example in a tracker for `rnaseqdiffexpression` https://github.com/CGATOxford/CGATPipelines/blob/94b975256fa5142f15e82511f4b62a6c19ae38b9/CGATPipelines/pipeline_docs/pipeline_rnaseqdiffexpression/trackers/Genelists.py#L5-L30. 

The `config.ini` for `pipeline_genesets` still contains an option for this table https://github.com/CGATOxford/CGATPipelines/blob/8ebe37408aa512ec910b767e07ade4d4b1733177/CGATPipelines/pipeline_genesets/pipeline.ini#L318 but the pipeline doesn't use this option and doesn't generate the table. This breaks at least one of my pipelines which integrates with pipeline_annotations/genesets. Is there any reason pipeline_genesets doesn't generate this table?

**Comment by Acribbs** [comment]
When developing the geneses pipeline the intention was to initially support the bare minimum needed for the CGAT-flow pipelines to work. It was removed because it wasn't used in pipelines and CGATreports isn't supported going forward. If you think you need it then feel free to add it back in. I am using the new cgat-developers code now though.

**Comment by TomSmithCGAT** [comment]
OK, I'll move this comment to cgat-developers
