### ISSUE TITLE
Shared Memory Usage in STAR

### ISSUE THREAD

**Issue by IanSudbery** [CGATOxford/CGATPipelines#53]
My STAR runs are failing with the error:

```
Shared memory error: 4, errno: Cannot allocate memory(12)
EXITING because of FATAL ERROR: problems with shared memory: error from shmget() or shm_open().
SOLUTION: check shared memory settings as explained in STAR manual, OR run STAR with --genomeLoad NoSharedMemory to avoid using shared memory

Jun 30 12:38:47 ...... FATAL ERROR, exiting
```

However, the --genomeLoad setting is hard coded in pipeline_mapping. 

Perhaps this is due to the memeory issues we are having? I've also been having fastqc jobs failing with errors suggestive of a lack of memory.

**Comment by Charlie-George** [comment]
My STAR runs are also doing the same, I think it’s all connected to the memory issues.

I did find this post  (https://github.com/alexdobin/STAR/issues/36)  and thought it may be a problem as the new STAR version was only recently installed,  but i rebuilt the index with the new version and it has made no difference to the memory errors, but perhaps I’ve misunderstood what the post meant?

On 30 Jun 2015, at 13:17, Ian Sudbery <notifications@github.com<mailto:notifications@github.com>> wrote:

My STAR runs are failing with the error:

Shared memory error: 4, errno: Cannot allocate memory(12)
EXITING because of FATAL ERROR: problems with shared memory: error from shmget() or shm_open().
SOLUTION: check shared memory settings as explained in STAR manual, OR run STAR with --genomeLoad NoSharedMemory to avoid using shared memory

Jun 30 12:38:47 ...... FATAL ERROR, exiting

However, the --genomeLoad setting is hard coded in pipeline_mapping.

Perhaps this is due to the memeory issues we are having? I've also been having fastqc jobs failing with errors suggestive of a lack of memory.

**Comment by AndreasHeger** [comment]
Thanks. From the man page of shm_open, the error suggests:

```
#define EINTR            4      /* Interrupted system call */
```

and 

```
[EINTR]
    The shm_open() operation was interrupted by a signal.
```

This could be due to the ulimit setting in Pipeline.py - is it disabled? If not, can you do so to check?

**Comment by Charlie-George** [comment]
Hi Andreas,

Yes I hashed out the ulimit setting in Pipeline.py and still got the error. STAR does map some files it’s just a proportion that give the error, but they seem to complete when you rerun them.

Thanks.

On 30 Jun 2015, at 14:17, Andreas Heger <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks. From the man page of shm_open, the error suggests:

#define EINTR            4      /\* Interrupted system call */

and

[EINTR]
    The shm_open() operation was interrupted by a signal.

This could be due to the ulimit setting in Pipeline.py - is it disabled? If not, can you do so to check?

**Comment by AndreasHeger** [comment]
Thanks. Can you keep monitoring this? Next time it fails we will look at the log-file to see which machine it was executed on and what the load status of the machine was.

**Comment by IanSudbery** [comment]
I just ran into this again, but i'm not sure how I find the machine it is being sent to from the logs.

**Comment by sebastian-luna-valero** [comment]
Hi,

I use:

```
grep HOSTNAME shell.log | grep -v PROMPT
```

but Andreas might want to confirm.

Best regards,
Sebastian.

**Comment by IanSudbery** [comment]
Its difficult to catch - i'm mapping 44 files and its difficult to know which are going to which nodes, but my feeling is that jobs going to the 24Gb nodes are failing. Given that we are asking for 22.8Gb of memory, perhaps that is not enough? The orignal spec for STAR says it needs ~30Gb for a human genome unless the index is generated in sparse mode. Have we generated new indexes with different options?

**Comment by IanSudbery** [comment]
Okay, I caught one in the act running on cgat112. It had a MEMUSE of 304.4M of 23.5GB, and a SWAPUS of 42.6M as reported by qhost.

I also got a slightly different error message. This time the error was:

```
EXITING: fatal error from shmget() trying to allocate shared memory piece: error typeCannot allocate memory
Possible cause 1: not enough RAM. Check if you have enough RAM of at least18817995016 bytes
Possible cause 2: not enough virtual memory allowed with ulimit. SOLUTION: run ulimit -v 18817995016
Possible cause 3: allowed shared memory size is not large enough. SOLUTIONS: (i) consult STAR manual on how to increase shared memory allocation; (ii) ask your system administrator to increase shared memory allocation; (iii) run STAR with --genomeLoad NoSharedMemory
```

18817995016 bytes is about 17.5GB so there was sufficient free RAM on the machine.

**Comment by IanSudbery** [comment]
I don't know if its realated, but I've just had a load of bwa jobs fail with out of memory as well.

**Comment by Charlie-George** [comment]
My files that were being mapped on 102 which has 24Gb were failing also, however I'm also getting a different memory error from a file mapped on 014 which has plenty of memory (I've lost it now but if it happens again I'll post it). I was using the hg38 index generated using  --genomeSAsparseD 2  which I think has been the default for all the indexes previously, although my index does not  filter _random and ChrUN so is a bit larger. However Jakub was also having this problem with mouse data from previously generated indexes that used to be fine.

To test whether this was a bug resulting from the recent STAR upgrade Andreas removed the new version from the module files, hence the different error message which i think is the same error just phased differently in STAR 2.4.0 compared to 2.4.2. - 2.4.2 is now back in the path.

Andreas is looking into the default ulimit setting to see if this is the problem.

Dr Charlotte L. George
CGAT Career Development Fellow | http://www.cgat.org
Functional Genomics Unit | University of Oxford
Tel: +44 1865 282362

**Comment by sebastian-luna-valero** [comment]
As announced in the emailing list, I have cleared up RAM space on some nodes and hopefully this will help with this problem.

Could you please adjust your "job_memory" requirements, try again and let me know if you find further problems?

Best regards,
Sebastian.

**Comment by jscaber** [comment]
Following these changes I have today successfully mapped 76 paired end files (fastq.1.gz file size 2.5G) with STAR with no errors. I did not set any specific "job_memory" requirements.
Best wishes,
Jakub

**Comment by IanSudbery** [comment]
Job_memory is set automatically in the mapping pipeline to max out the
smaller nodes at 23GB. This should be sufficient as the memory usage of
STAR on a human genome, given our index building options, should be 18GB.

_From:_ Jakub Scaber [mailto:notifications@github.com]
_Sent:_ 06 July 2015 17:12
_To:_ CGATOxford/CGATPipelines
_Cc:_ Ian Sudbery
_Subject:_ Re: [CGATPipelines] Shared Memory Usage in STAR (#53)

Following these changes I have today successfully mapped 76 paired end
files (fastq.1.gz file size 2.5G) with STAR with no errors. I did not set
any specific "job_memory" requirements.
Best wishes,
Jakub

**Comment by AndreasHeger** [comment]
Thanks, this seems to be resolved.
