### ISSUE TITLE
pipeline_mapping & pipeline_rnaseqtranscripts - Fasta references

### ISSUE THREAD

**Issue by Charlie-George** [CGATOxford/CGATPipelines#59]
In several places the pipelines refer to the bowtie_index_file location for fasta and index files - this is fine if bowtie genome was used to generate files, however often these have been prefiltered to only contain standard chromosome (excluding ChrUn and _random, chrM) - if you have used a different genome to map to (e.g. that includes these other contigs) tasks such as PicardStats will fail. The ini files contain sections that imply you can filter the genome references to contain what you like, however these options don't work if the fast has already been filtered at an earlier step.

**Comment by IanSudbery** [comment]
Once upon a time, the index directory would contain the fa file used to generate the index. But i've noticed that something is deleting them from at least the star directory (its not the Makefile as far as I can tell).

**Comment by AndreasHeger** [comment]
Which particular file?

**Comment by IanSudbery** [comment]
hg19.fa in the star indexes. Its really odd. I ran the Makefile, hg.fa was created from the faidx directory, and the index made. The next time I looked in the directory the hg19.fa was gone. As are all the other fasta files.

**Comment by AndreasHeger** [comment]
The index directory is fairly new. I did rearrange the .fa files to remove duplication, please see the CGAT-README file.

I have recreated them (using `make h19.fa`), let us see if they stay.

**Comment by IanSudbery** [comment]
Sorry, I just twigged something. When I said the 'indexes' directory, I didn't mean `/ifs/mirror/genomes/indexes`, whose existance I wasn't aware of, but rather `/ifs/mirror/genomes/sta`r. I now see that there is now a `hg19.fa` in there which is linked to `/indexes`. My confusion came about because I was building star indexes in the `/star/star_2.4.2_indexes directory`. The `Makefile` in that directory doesn't link the `indexes` directory, but rather regenerates the `.fa` file. 

So, 
1) Should these Makefiles be altered to link the indexes directory
2) Should I be building new indexes in the `/star/star_2.4.2_indexes` directory
3) Why do the `.fa` files generated in the `/star/star_2.4.2` directory disappear?

**Comment by AndreasHeger** [comment]
1) Yes, please link to the .fa files in the indexes directory. It is important to work from one .fa file across mappers and fasta files in order to have the exact number of chromosomes. Otherwise, tools like Picard complain.

2) To keep with bwa convention, use the directory /ifs/mirror/genomes/star-2.4.2, rename the old one to start-X.Y.Z and create a link of "star" to the most recent directory. This way, everybody will automatically pick up the most recent indices (appropriate for the latest version of star). If somebody needs to go back, they can specify the old version directly.

3) Possibility: Make deletes intermediate files once the target has been successfully build. To keep intermediate files, they need to explicitely be part of the target list or dependencies of the .PRECIOUS target.

**Comment by IanSudbery** [comment]
Hmm... Looks like STAR recommends keeping ChrUN and _random, while bowtie recommends removing them. What do people think about this?

**Comment by TomSmithCGAT** [comment]
Personally, I'm in favour of keeping the ChrUN and _random contigs in the index. Leaving them out risks "forcing" reads originating from these contigs to align to the proerly assembled contigs erroneously. I take it that's the rationale behind STAR's recommendation too?

**Comment by AndreasHeger** [comment]
I found the following comment [here](http://homer.salk.edu/homer/basicTutorial/mapping.html)
"""
I also tend to remove the "*_random.fa" chromosomes.  These often contain part of the canonical chromosomes in addition to regions that cannot be placed in the assembly.  The problem with these regions is that the part shared with the canonical chromosome will be present twice, making it difficult to map the reads to a unique location.
"""
It might be application specific. For shorter reads such as ChIP-seq it might be better to keep them out, but for long-reads like in RNA-seq better to keep them in.

**Comment by TomSmithCGAT** [comment]
Umm... I hadn't considered that. The canonical sequence is contained in the "_random.fa" chromosome by accident of misassembly I take it?

**Comment by AndreasHeger** [comment]
I am not sure, and I am not sure if this is true and to what extent, how large the regions are, etc. I did not find any more references to this. Might be worth looking at dotter to get a feel for this.
